# This is the docker config used for the lab
# Use it like 'docker-compose -f docker-compose.yml -f docker-compose.lab.yml up [-d] [services]'
version: '3'
services:
  asp:
    build:
      dockerfile: ./dockerfiles/Asp.Lab.dockerfile

  titanoboa:
    build:
      dockerfile: ./dockerfiles/Titanoboa.Lab.dockerfile
    environment:
      USING_QUOTE_SRV: 'TRUE'
      SERVER_NAME: 'TIT'

  twig:
    build:
      dockerfile: ./dockerfiles/Twig.Lab.dockerfile
      
