version: '3'
services:
  rabbit:
    image: 'rabbitmq:3.7-management'
    environment:
      RABBITMQ_DEFAULT_USER: scaley
      RABBITMQ_DEFAULT_PASS: abilities
    ports:
      - '5672:5672'
      - '15672:15672'

  database:
    image: 'postgres:11.1'
    environment:
      POSTGRES_DB: 'scaley_abilities'
      POSTGRES_USER: 'scaley'
      POSTGRES_PASSWORD: 'abilities'
    ports:
      - '5432:5432'

  database_admin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'scaley@abilities.com'
      PGADMIN_DEFAULT_PASSWORD: 'abilities'
    ports:
      - '15432:80'
  
  asp:
    build:
      context: .
      dockerfile: ./dockerfiles/Asp.dockerfile
    environment:
      RABBIT_HOST: 'rabbit'
      INSTANCES: '1'
    ports:
      - '80:80'

  titanoboa:
    build:
      context: .
      dockerfile: ./dockerfiles/Titanoboa.dockerfile
    depends_on:
      - 'database'
    environment:
      RABBIT_HOST: 'rabbit'
      SQL_HOST: 'database'
      QUOTE_API: 'http://cobra:5588'

  twig:
    build:
      context: .
      dockerfile: ./dockerfiles/Twig.dockerfile
    environment:
      RABBIT_HOST: 'rabbit'
      QUOTE_API: 'http://cobra:5588'

  cobra:
    build:
      context: .
      dockerfile: ./dockerfiles/Cobra.dockerfile
    environment:
      RABBIT_HOST: 'rabbit'
    ports:
      - '5588:5588'

  lora:
    build:
      context: .
      dockerfile: ./dockerfiles/Lora.dockerfile
    environment:
      RABBIT_HOST: 'rabbit'
    volumes:
      - './logs:/app/logs'

  woma:
    build:
      context: .
      dockerfile: ./dockerfiles/Woma.dockerfile
    environment:
      RABBIT_HOST: 'rabbit'