version: '3'
services:
  rabbit:
    image: 'rabbitmq:3.7-management'
    environment:
      RABBITMQ_DEFAULT_USER: scaley
      RABBITMQ_DEFAULT_PASS: abilities
    ports:
      - '5672:5672'
      - '15672:15672'

  database:
    image: 'mariadb:10.4'
    environment:
      MYSQL_DATABASE: 'scaley_abilities'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: 'scaley'
      MYSQL_PASSWORD: 'abilities'
    ports:
      - '3306:3306'

  asp:
    build:
      context: .
      dockerfile: ./dockerfiles/Asp.dockerfile
    depends_on:
      - 'rabbit'
    environment:
      RABBIT_HOST: 'rabbit'
    ports:
      - '80:80'

  titanoboa:
    build:
      context: .
      dockerfile: ./dockerfiles/Titanoboa.dockerfile
    depends_on:
      - 'rabbit'
      - 'database'
    environment:
      RABBIT_HOST: 'rabbit'
      SQL_HOST: 'database'
