version: '3'
services:
  rabbit:
    image: 'rabbitmq:3.7-management'
    environment:
      RABBITMQ_DEFAULT_USER: scaley
      RABBITMQ_DEFAULT_PASS: abilities

  database:
    image: 'mariadb:10.4'
    environment:
      MYSQL_DATABASE: 'scaley_abilities'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: 'scaley'
      MYSQL_PASSWORD: 'abilities'
