# These overrides are automatically applied when you do docker-compose up
# These are the docker configurations we use for development
version: '3'
services:
  rabbit:
    ports:
      - '5672:5672'
      - '15672:15672'

  database:
    ports:
      - '3306:3306'
